@startuml システム全体シーケンス図

box メインマシン（自宅）
participant 検索
participant Jenkins_Job
participant レポート作成
end box
participant レンタルサーバー


activate 検索
note over 検索: 検索は常時実行
activate レンタルサーバー
note over レンタルサーバー: 常時稼働

Jenkins_Job -> Jenkins_Job : Fire
loop おおむね15分間隔

Jenkins_Job -> レポート作成 : 定期実行

activate Jenkins_Job
activate レポート作成
レポート作成 -> 検索 : 状況伺い
検索 -> レポート作成 : 進捗データ
レポート作成 -> レポート作成 : 静的HTML作成
レポート作成 -> Jenkins_Job : 静的HTML提供

deactivate レポート作成

Jenkins_Job -> レンタルサーバー : FTP Upload
deactivate Jenkins_Job
note over レンタルサーバー: ページが更新される

end

@enduml
